Работа со строкой запроса
htmlacademy-php/608749-readme-12 pull request #10
Opened 2021-05-31 17:38 UTC by tinakuzmenko

Задание довольно объемное, поэтому вот вкратце резюме по поводу того, что входит в ПР.

Что реализовано: 

- Показ 6 популярных постов на странице "Популярное".
- Отображение количества лайков и комментариев у каждого поста на главной странице.
- Фильтрация популярных постов по типу.
- Переход на пост по нажатию на его название.
- Показ выбранного поста: название, текст, количество просмотров, количество лайков и комментариев.
- Хэштеги.
- Показ комментариев к посту: имя пользователя, дата комментария, текст комментария.
- Информация о пользователе, который опубликовал пост.
- Добавлен пример поста с видео.
- Проверка отображения ошибок при запросах или если пост с нужным id не найден.
- Сортировка и ее совместная работа с фильтрами на главной странице.

Что пока что не реализовано: 

- Показ репостов у того или иного поста (не добавляли в БД такую сущность).
- Кнопка "Показать все комментарии" (не нашла в ТЗ о ней).
- Пагинация популярных постов на главной (пока что реализация только показа пагинации, если постов больше, чем лимит).

2021-05-31 23:14 UTC, ademaro requested changes
Отличная работа, молодец! Только давай не войну и мир скидывать в одном ПР, а чуть разбивай что ли)) Сложно такой дифф смотреть, конечно))

Давай тогда подправим моменты и двинем дальше, ПР пока открытый оставляю.

2021-05-31 23:14 UTC, ademaro commented on index.php
> +        $comments = get_post_comments($link, $post['id']);
для каждого поста делаем запрос на все комменты, что бы получить просто количество?) 100 постов, например, будет минимум 100 запросов к БД) Можно сделать одним запросом. Давай подумаем.

2021-05-31 23:14 UTC, ademaro commented on models.php
> +    $sort = $sort_param === 'likes' ? " ORDER BY likes $direction" : " ORDER BY $sort_param $direction";
что-то я не понимаю зачем так усложнили, если это то же самое что и 
`$sort = " ORDER BY $sort_param $direction";`

2021-05-31 23:14 UTC, ademaro commented on models.php
> +              ? = 0 AND content_type_id > 0 ' . $sort . ' LIMIT 6';
что за 6? — давай в константу, может?

2021-05-31 23:14 UTC, ademaro commented on models.php
> +        $params['filter']
эти две строчки для чего?

2021-05-31 23:14 UTC, ademaro commented on templates/errors/not-found.php
> +<main class="page__main page__main--search-results">
ещё HTTP 404 ответ отдать бы браузеру)

2021-05-31 23:14 UTC, ademaro commented on templates/main.php
> +                            ]); ?>"
ну прям чувствуется реакт)) вообще желательно вынести это в контроллер...

2021-05-31 23:14 UTC, ademaro commented on templates/post-details.php
> +                    <?php endif; ?>
начинаем думать как разделить данные от логики...

2021-05-31 23:14 UTC, ademaro commented on templates/post-details.php
> +                                    <?= include_template('post/comment.php', [
Может, просто `<?= include_template('post/comment.php', $comment); ?>` ?

2021-05-31 23:14 UTC, ademaro commented on user-functions.php
> +function build_query(array $params): string {
разд добавления `/?` к строке — сделали отдельную функцию?) Попахивает велосипедостроением))

2021-06-08 15:37 UTC, tinakuzmenko commented on models.php
> +        $params['filter']
Каждая вставка параметра в запрос - отдельный аргумент. Даже если аргумент один и тот же, мы должны передавать его отдельным элементом массива. Пока не нашла другого решения.

2021-06-13 17:42 UTC, ademaro approved these changes
LGTM

2021-06-13 17:42 UTC, merged