Создаём схему БД личного проекта
htmlacademy-php/608749-readme-12 pull request #7
Opened 2021-04-13 19:34 UTC by tinakuzmenko

- Внесла правки;
- Создала схему БД.

2021-04-14 19:45 UTC, ademaro commented on schema.sql
> +CREATE DATABASE readme
Почитай про DROP DATABASE IF EXEST

2021-04-14 19:46 UTC, ademaro commented on schema.sql
> +    password     CHAR(64)     NOT NULL,
Чем CHAR от VARCHAR отличается?)

2021-04-14 19:47 UTC, ademaro commented on schema.sql
> +    picture         TEXT,
Почему тут TEXT? И ниже?

2021-04-14 19:48 UTC, ademaro commented on schema.sql
> +    type CHAR NOT NULL UNIQUE,
для CHAR надо длину указать

2021-04-14 19:50 UTC, ademaro requested changes
Давай сразу подправим микро-мелочи и двинем дальше) В целом — всё очень круто, молодец!

2021-04-17 16:29 UTC, tinakuzmenko commented on schema.sql
> +    password     CHAR(64)     NOT NULL,
Насколько я поняла, у CHAR фиксированный размер, у VARCHAR вариативный размер. Вроде как VARCHAR оптимальнее и гибче, потому везде использую его. В некоторых случаях, конечно, лучше CHAR, но у нас я таких вариантов не вижу. :)

2021-04-19 08:59 UTC, ademaro commented on schema.sql
> +DROP DATABASE IF EXISTS readme;
👍🏼

2021-04-19 13:32 UTC, ademaro commented on schema.sql
> +    password     VARCHAR(64)     NOT NULL,
тут как раз подошёл бы CHAR, что бы не было лишней фрагментации. Но на наших данных это не принципиально вообще, VARCHAR — хороший выбор

2021-04-19 13:32 UTC, ademaro approved these changes

2021-04-19 13:32 UTC, merged